/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cryptographie.DiffieHellman;

import java.text.DecimalFormat;
import java.text.NumberFormat;

/**
 *
 * @author dj715494
 */
public class Attaque_Homme_Milieu extends javax.swing.JFrame {

    /**
     * Creates new form Attaque_Homme_Milieu
     */
    public Attaque_Homme_Milieu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lNbCommune = new javax.swing.JLabel();
        lAlice = new javax.swing.JLabel();
        jEve = new javax.swing.JLabel();
        lBob = new javax.swing.JLabel();
        jNbCommun = new javax.swing.JTextField();
        lNbSecret = new javax.swing.JLabel();
        jNbSecretAlice = new javax.swing.JTextField();
        jNbSecretEveToAlice = new javax.swing.JTextField();
        jNbSecretEveToBob = new javax.swing.JTextField();
        jNbSecretBob = new javax.swing.JTextField();
        jButtonAlice = new javax.swing.JButton();
        jButtonEveToAlice = new javax.swing.JButton();
        jButtonEveToBob = new javax.swing.JButton();
        jButtonBob = new javax.swing.JButton();
        lCleInter = new javax.swing.JLabel();
        jCleInterAlice = new javax.swing.JLabel();
        jCleInterEveToAlice = new javax.swing.JLabel();
        jCleInterEveToBob = new javax.swing.JLabel();
        jCleInterBob = new javax.swing.JLabel();
        jButtonAliceTransmettre = new javax.swing.JButton();
        jButtonEveToAliceTransmettre = new javax.swing.JButton();
        jButtonEveToBobTransmettre = new javax.swing.JButton();
        jButtonBobTransmettre = new javax.swing.JButton();
        lNbAmi = new javax.swing.JLabel();
        jNbAmiAlice = new javax.swing.JTextField();
        jNbAmiEveToAlice = new javax.swing.JTextField();
        jNbAmiEveToBob = new javax.swing.JTextField();
        jNbAmiBob = new javax.swing.JTextField();
        jButtonCleAlice = new javax.swing.JButton();
        jButtonCleEveToAlice = new javax.swing.JButton();
        jButtonCleEveToBob = new javax.swing.JButton();
        jButtonCleBob = new javax.swing.JButton();
        lCle = new javax.swing.JLabel();
        jCleAlice = new javax.swing.JLabel();
        jCleEveToBob = new javax.swing.JLabel();
        jCleEveToAlice = new javax.swing.JLabel();
        jCleBob = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lNbCommune.setText("Entrer le nombre commun");

        lAlice.setText("Alice");

        jEve.setText("Eve");

        lBob.setText("Bob");

        lNbSecret.setText("Entrer votre nombre secret");

        jButtonAlice.setText("Générer");
        jButtonAlice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAliceActionPerformed(evt);
            }
        });

        jButtonEveToAlice.setText("Générer");
        jButtonEveToAlice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEveToAliceActionPerformed(evt);
            }
        });

        jButtonEveToBob.setText("Générer");
        jButtonEveToBob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEveToBobActionPerformed(evt);
            }
        });

        jButtonBob.setText("Générer");
        jButtonBob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBobActionPerformed(evt);
            }
        });

        lCleInter.setText("Donner ce nombre à votre ami");

        jButtonAliceTransmettre.setText("Transmettre");
        jButtonAliceTransmettre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAliceTransmettreActionPerformed(evt);
            }
        });

        jButtonEveToAliceTransmettre.setText("Transmettre");
        jButtonEveToAliceTransmettre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEveToAliceTransmettreActionPerformed(evt);
            }
        });

        jButtonEveToBobTransmettre.setText("Transmettre");
        jButtonEveToBobTransmettre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEveToBobTransmettreActionPerformed(evt);
            }
        });

        jButtonBobTransmettre.setText("Transmettre");
        jButtonBobTransmettre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBobTransmettreActionPerformed(evt);
            }
        });

        lNbAmi.setText("Entrer le nombre de votre ami");

        jButtonCleAlice.setText("Calculer");
        jButtonCleAlice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCleAliceActionPerformed(evt);
            }
        });

        jButtonCleEveToAlice.setText("Calculer");
        jButtonCleEveToAlice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCleEveToAliceActionPerformed(evt);
            }
        });

        jButtonCleEveToBob.setText("Calculer");
        jButtonCleEveToBob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCleEveToBobActionPerformed(evt);
            }
        });

        jButtonCleBob.setText("Calculer");
        jButtonCleBob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCleBobActionPerformed(evt);
            }
        });

        lCle.setText("Votre clé de cryptage");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(lAlice)
                .addGap(264, 264, 264)
                .addComponent(jEve)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lBob)
                .addGap(120, 120, 120))
            .addGroup(layout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addComponent(jButtonAlice)
                .addGap(116, 116, 116)
                .addComponent(jButtonEveToAlice)
                .addGap(122, 122, 122)
                .addComponent(jButtonEveToBob)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonBob)
                .addGap(91, 91, 91))
            .addGroup(layout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addComponent(jButtonAliceTransmettre)
                .addGap(95, 95, 95)
                .addComponent(jButtonEveToAliceTransmettre)
                .addGap(105, 105, 105)
                .addComponent(jButtonEveToBobTransmettre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addComponent(jButtonBobTransmettre)
                .addGap(80, 80, 80))
            .addGroup(layout.createSequentialGroup()
                .addGap(217, 217, 217)
                .addComponent(jButtonCleAlice)
                .addGap(119, 119, 119)
                .addComponent(jButtonCleEveToAlice)
                .addGap(118, 118, 118)
                .addComponent(jButtonCleEveToBob)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonCleBob)
                .addGap(90, 90, 90))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lNbCommune)
                        .addGap(271, 271, 271)
                        .addComponent(jNbCommun, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lNbSecret)
                            .addComponent(lCleInter)
                            .addComponent(lNbAmi)
                            .addComponent(lCle))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jNbSecretAlice, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                            .addComponent(jCleInterAlice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jNbAmiAlice)
                            .addComponent(jCleAlice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jNbSecretEveToAlice, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                            .addComponent(jCleInterEveToAlice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jNbAmiEveToAlice)
                            .addComponent(jCleEveToAlice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jNbSecretEveToBob, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                            .addComponent(jCleInterEveToBob, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jNbAmiEveToBob)
                            .addComponent(jCleEveToBob, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jNbSecretBob, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                            .addComponent(jCleInterBob, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jNbAmiBob)
                            .addComponent(jCleBob, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(54, 54, 54))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCleEveToAlice, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lAlice)
                            .addComponent(jEve)
                            .addComponent(lBob))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lNbCommune)
                                    .addComponent(jNbCommun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lNbSecret)
                                    .addComponent(jNbSecretAlice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jNbSecretEveToAlice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jNbSecretEveToBob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jNbSecretBob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButtonAlice)
                                    .addComponent(jButtonEveToAlice)
                                    .addComponent(jButtonEveToBob)
                                    .addComponent(jButtonBob))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jCleInterBob, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jCleInterEveToBob, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jCleInterEveToAlice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lCleInter)
                                        .addComponent(jCleInterAlice, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButtonAliceTransmettre)
                                    .addComponent(jButtonEveToAliceTransmettre)
                                    .addComponent(jButtonEveToBobTransmettre)
                                    .addComponent(jButtonBobTransmettre))
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lNbAmi)
                                    .addComponent(jNbAmiAlice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jNbAmiEveToAlice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jNbAmiEveToBob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jNbAmiBob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButtonCleAlice)
                                    .addComponent(jButtonCleEveToAlice)
                                    .addComponent(jButtonCleEveToBob)
                                    .addComponent(jButtonCleBob))
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lCle)
                                        .addComponent(jCleAlice, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jCleEveToBob, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCleBob, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAliceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAliceActionPerformed
        NumberFormat formatter = new DecimalFormat("#0");
        if(!this.jNbCommun.getText().isEmpty() && !this.jNbSecretAlice.getText().isEmpty()){
            double cleInterAlice = DiffieHellman.calculCle(Double.valueOf(this.jNbCommun.getText()), Double.valueOf(this.jNbSecretAlice.getText()));
            this.jCleInterAlice.setText(formatter.format(cleInterAlice));
        }
    }//GEN-LAST:event_jButtonAliceActionPerformed

    private void jButtonEveToAliceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEveToAliceActionPerformed
        NumberFormat formatter = new DecimalFormat("#0");
        if(!this.jNbCommun.getText().isEmpty() && !this.jNbSecretEveToAlice.getText().isEmpty()){
            double cleInterEveToAlice = DiffieHellman.calculCle(Double.valueOf(this.jNbCommun.getText()), Double.valueOf(this.jNbSecretEveToAlice.getText()));
            this.jCleInterEveToAlice.setText(formatter.format(cleInterEveToAlice));
        }
    }//GEN-LAST:event_jButtonEveToAliceActionPerformed

    private void jButtonEveToBobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEveToBobActionPerformed
        NumberFormat formatter = new DecimalFormat("#0");
        if(!this.jNbCommun.getText().isEmpty() && !this.jNbSecretEveToBob.getText().isEmpty()){
            double cleInterEveToBob = DiffieHellman.calculCle(Double.valueOf(this.jNbCommun.getText()), Double.valueOf(this.jNbSecretEveToBob.getText()));
            this.jCleInterEveToBob.setText(formatter.format(cleInterEveToBob));
        }
    }//GEN-LAST:event_jButtonEveToBobActionPerformed

    private void jButtonBobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBobActionPerformed
        NumberFormat formatter = new DecimalFormat("#0");
        if(!this.jNbCommun.getText().isEmpty() && !this.jNbSecretBob.getText().isEmpty()){
            double cleInterBob = DiffieHellman.calculCle(Double.valueOf(this.jNbCommun.getText()), Double.valueOf(this.jNbSecretBob.getText()));
            this.jCleInterBob.setText(formatter.format(cleInterBob));
        }
    }//GEN-LAST:event_jButtonBobActionPerformed

    private void jButtonAliceTransmettreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAliceTransmettreActionPerformed
        if(!this.jCleInterAlice.getText().isEmpty()){
            this.jNbAmiEveToAlice.setText(this.jCleInterAlice.getText());
        }
    }//GEN-LAST:event_jButtonAliceTransmettreActionPerformed

    private void jButtonEveToAliceTransmettreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEveToAliceTransmettreActionPerformed
        if(!this.jCleInterEveToAlice.getText().isEmpty()){
            this.jNbAmiAlice.setText(this.jCleInterEveToAlice.getText());
        }
    }//GEN-LAST:event_jButtonEveToAliceTransmettreActionPerformed

    private void jButtonEveToBobTransmettreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEveToBobTransmettreActionPerformed
        if(!this.jCleInterEveToBob.getText().isEmpty()){
            this.jNbAmiBob.setText(this.jCleInterEveToBob.getText());
        }
    }//GEN-LAST:event_jButtonEveToBobTransmettreActionPerformed

    private void jButtonBobTransmettreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBobTransmettreActionPerformed
        if(!this.jCleInterBob.getText().isEmpty()){
            this.jNbAmiEveToBob.setText(this.jCleInterBob.getText());
        }
    }//GEN-LAST:event_jButtonBobTransmettreActionPerformed

    private void jButtonCleAliceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCleAliceActionPerformed
        NumberFormat formatter = new DecimalFormat("#0");
        if(!this.jNbAmiAlice.getText().isEmpty() && !this.jNbSecretAlice.getText().isEmpty()){
            double cleAlice = DiffieHellman.calculCle(Double.valueOf(this.jNbAmiAlice.getText()), Double.valueOf(this.jNbSecretAlice.getText()));
            this.jCleAlice.setText(formatter.format(cleAlice));
        }
    }//GEN-LAST:event_jButtonCleAliceActionPerformed

    private void jButtonCleEveToAliceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCleEveToAliceActionPerformed
        NumberFormat formatter = new DecimalFormat("#0");
        if(!this.jNbAmiEveToAlice.getText().isEmpty() && !this.jNbSecretEveToAlice.getText().isEmpty()){
            double cleEveToAlice = DiffieHellman.calculCle(Double.valueOf(this.jNbAmiEveToAlice.getText()), Double.valueOf(this.jNbSecretEveToAlice.getText()));
            this.jCleEveToAlice.setText(formatter.format(cleEveToAlice));
        }
    }//GEN-LAST:event_jButtonCleEveToAliceActionPerformed

    private void jButtonCleEveToBobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCleEveToBobActionPerformed
        NumberFormat formatter = new DecimalFormat("#0");
        if(!this.jNbAmiEveToBob.getText().isEmpty() && !this.jNbSecretEveToBob.getText().isEmpty()){
            double cleEveToBob = DiffieHellman.calculCle(Double.valueOf(this.jNbAmiEveToBob.getText()), Double.valueOf(this.jNbSecretEveToBob.getText()));
            this.jCleEveToBob.setText(formatter.format(cleEveToBob));
        }
    }//GEN-LAST:event_jButtonCleEveToBobActionPerformed

    private void jButtonCleBobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCleBobActionPerformed
        NumberFormat formatter = new DecimalFormat("#0");
        if(!this.jNbAmiBob.getText().isEmpty() && !this.jNbSecretBob.getText().isEmpty()){
            double cleBob = DiffieHellman.calculCle(Double.valueOf(this.jNbAmiBob.getText()), Double.valueOf(this.jNbSecretBob.getText()));
            this.jCleBob.setText(formatter.format(cleBob));
        }
    }//GEN-LAST:event_jButtonCleBobActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Attaque_Homme_Milieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Attaque_Homme_Milieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Attaque_Homme_Milieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Attaque_Homme_Milieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Attaque_Homme_Milieu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlice;
    private javax.swing.JButton jButtonAliceTransmettre;
    private javax.swing.JButton jButtonBob;
    private javax.swing.JButton jButtonBobTransmettre;
    private javax.swing.JButton jButtonCleAlice;
    private javax.swing.JButton jButtonCleBob;
    private javax.swing.JButton jButtonCleEveToAlice;
    private javax.swing.JButton jButtonCleEveToBob;
    private javax.swing.JButton jButtonEveToAlice;
    private javax.swing.JButton jButtonEveToAliceTransmettre;
    private javax.swing.JButton jButtonEveToBob;
    private javax.swing.JButton jButtonEveToBobTransmettre;
    private javax.swing.JLabel jCleAlice;
    private javax.swing.JLabel jCleBob;
    private javax.swing.JLabel jCleEveToAlice;
    private javax.swing.JLabel jCleEveToBob;
    private javax.swing.JLabel jCleInterAlice;
    private javax.swing.JLabel jCleInterBob;
    private javax.swing.JLabel jCleInterEveToAlice;
    private javax.swing.JLabel jCleInterEveToBob;
    private javax.swing.JLabel jEve;
    private javax.swing.JTextField jNbAmiAlice;
    private javax.swing.JTextField jNbAmiBob;
    private javax.swing.JTextField jNbAmiEveToAlice;
    private javax.swing.JTextField jNbAmiEveToBob;
    private javax.swing.JTextField jNbCommun;
    private javax.swing.JTextField jNbSecretAlice;
    private javax.swing.JTextField jNbSecretBob;
    private javax.swing.JTextField jNbSecretEveToAlice;
    private javax.swing.JTextField jNbSecretEveToBob;
    private javax.swing.JLabel lAlice;
    private javax.swing.JLabel lBob;
    private javax.swing.JLabel lCle;
    private javax.swing.JLabel lCleInter;
    private javax.swing.JLabel lNbAmi;
    private javax.swing.JLabel lNbCommune;
    private javax.swing.JLabel lNbSecret;
    // End of variables declaration//GEN-END:variables
}
