/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cryptographie.DiffieHellman;

/**
 *
 * @author yv066840
 */
public class Fenetre extends javax.swing.JFrame {

    /**
     * Creates new form Fenetre
     */
    public Fenetre() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lNbCommun = new javax.swing.JLabel();
        jNbCommun = new javax.swing.JTextField();
        lNbPerso = new javax.swing.JLabel();
        jNbPerso = new javax.swing.JTextField();
        lCleInter = new javax.swing.JLabel();
        rCleInter = new javax.swing.JLabel();
        lNbAmi = new javax.swing.JLabel();
        jNbAmi = new javax.swing.JTextField();
        lCle = new javax.swing.JLabel();
        jCle = new javax.swing.JLabel();
        jButtonCleInter = new javax.swing.JButton();
        jButtonCle = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lNbCommun.setText("Entrer votre nombre commun");

        lNbPerso.setText("Entrer votre nombre secret");

        lCleInter.setText("Donner cette valeur à votre ami");

        lNbAmi.setText("Entrer le nombre de votre ami");

        lCle.setText("Votre cle commune");

        jButtonCleInter.setText("Valider");
        jButtonCleInter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCleInterActionPerformed(evt);
            }
        });

        jButtonCle.setText("Valider");
        jButtonCle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lNbCommun)
                    .addComponent(lNbPerso)
                    .addComponent(lCleInter)
                    .addComponent(lNbAmi)
                    .addComponent(lCle))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonCle)
                    .addComponent(jButtonCleInter)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jNbCommun, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                        .addComponent(jNbPerso)
                        .addComponent(rCleInter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jNbAmi)
                        .addComponent(jCle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNbCommun)
                    .addComponent(jNbCommun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNbPerso)
                    .addComponent(jNbPerso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonCleInter)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lCleInter)
                    .addComponent(rCleInter, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNbAmi)
                    .addComponent(jNbAmi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jButtonCle)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lCle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(132, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCleInterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCleInterActionPerformed
        if(!this.jNbCommun.getText().isEmpty() && !this.jNbPerso.getText().isEmpty()){
            int temp = Aled.calculCléInter(Integer.valueOf(this.jNbCommun.getText()), Integer.valueOf(this.jNbPerso.getText()));
            this.rCleInter.setText(Integer.toString(temp));
        }
    }//GEN-LAST:event_jButtonCleInterActionPerformed

    private void jButtonCleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCleActionPerformed
        if(!this.rCleInter.getText().isEmpty() && !this.jNbAmi.getText().isEmpty()){
            int temp = Aled.calculCle(Integer.valueOf(this.jNbAmi.getText()), Integer.valueOf(this.jNbPerso.getText()));
            this.jCle.setText(Integer.toString(temp));
        }
    }//GEN-LAST:event_jButtonCleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fenetre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCle;
    private javax.swing.JButton jButtonCleInter;
    private javax.swing.JLabel jCle;
    private javax.swing.JTextField jNbAmi;
    private javax.swing.JTextField jNbCommun;
    private javax.swing.JTextField jNbPerso;
    private javax.swing.JLabel lCle;
    private javax.swing.JLabel lCleInter;
    private javax.swing.JLabel lNbAmi;
    private javax.swing.JLabel lNbCommun;
    private javax.swing.JLabel lNbPerso;
    private javax.swing.JLabel rCleInter;
    // End of variables declaration//GEN-END:variables
}
