/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cryptographie.Transposition;

/**
 *
 * @author Damien
 */
public class Cryptage_Transposition extends javax.swing.JFrame {

    /**
     * Creates new form Cryptage_Transposition
     */
    public Cryptage_Transposition() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lCle = new javax.swing.JLabel();
        jCle = new javax.swing.JTextField();
        lMessage = new javax.swing.JLabel();
        lCrypte = new javax.swing.JLabel();
        jMessage = new javax.swing.JTextField();
        jMessageCrypte = new javax.swing.JTextField();
        lMessageDecrypte = new javax.swing.JLabel();
        jMessageDecrypte = new javax.swing.JTextField();
        jButtonCrypte = new javax.swing.JButton();
        jButtonDecrypte = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lCle.setText("Entrer la clé de cryptage");

        lMessage.setText("Entrer le message à crypter");

        lCrypte.setText("Message crypté");

        lMessageDecrypte.setText("Message decrypté");

        jButtonCrypte.setText("Chiffrement");
        jButtonCrypte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrypteActionPerformed(evt);
            }
        });

        jButtonDecrypte.setText("Dechiffrement");
        jButtonDecrypte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDecrypteActionPerformed(evt);
            }
        });

        jButtonClear.setText("Clear");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lCle)
                    .addComponent(lCrypte)
                    .addComponent(lMessage)
                    .addComponent(lMessageDecrypte))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCle)
                    .addComponent(jMessage)
                    .addComponent(jMessageCrypte)
                    .addComponent(jMessageDecrypte, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE))
                .addGap(27, 27, 27))
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jButtonClear)
                .addGap(125, 125, 125)
                .addComponent(jButtonCrypte)
                .addGap(70, 70, 70)
                .addComponent(jButtonDecrypte)
                .addContainerGap(106, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lCle)
                    .addComponent(jCle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lMessage)
                    .addComponent(jMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lCrypte)
                    .addComponent(jMessageCrypte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lMessageDecrypte)
                    .addComponent(jMessageDecrypte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCrypte)
                    .addComponent(jButtonDecrypte)
                    .addComponent(jButtonClear))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCrypteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrypteActionPerformed
        if(!this.jCle.getText().isEmpty() && !this.jMessage.getText().isEmpty()){
            this.jMessageCrypte.setText(Crypteur_Transpo.cryptage(this.jCle.getText(), this.jMessage.getText()));
        }
    }//GEN-LAST:event_jButtonCrypteActionPerformed

    private void jButtonDecrypteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDecrypteActionPerformed
        if(!this.jCle.getText().isEmpty() && !this.jMessageCrypte.getText().isEmpty()){
            this.jMessageDecrypte.setText(Crypteur_Transpo.decryptage(this.jCle.getText(), this.jMessageCrypte.getText()));
        }
    }//GEN-LAST:event_jButtonDecrypteActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        this.jCle.setText("");
        this.jMessage.setText("");
        this.jMessageCrypte.setText("");
        this.jMessageDecrypte.setText("");
    }//GEN-LAST:event_jButtonClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cryptage_Transposition.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cryptage_Transposition.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cryptage_Transposition.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cryptage_Transposition.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cryptage_Transposition().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonCrypte;
    private javax.swing.JButton jButtonDecrypte;
    private javax.swing.JTextField jCle;
    private javax.swing.JTextField jMessage;
    private javax.swing.JTextField jMessageCrypte;
    private javax.swing.JTextField jMessageDecrypte;
    private javax.swing.JLabel lCle;
    private javax.swing.JLabel lCrypte;
    private javax.swing.JLabel lMessage;
    private javax.swing.JLabel lMessageDecrypte;
    // End of variables declaration//GEN-END:variables
}
